### PR TITLE
Collapsable sections

### PR DESCRIPTION
**Pull request by stspasow**
#42

### CODE REVIEW

**Comment by rishavanand** [comment]
@stspasow please rebase

**Comment by rishavanand** [comment]
@stspasow it doesn't seem to be working properly. Can you check again?

**Comment by stspasow** [comment]
It appears that sectionIndex that is passed in toggleNameToMarkdown and other functions is always undefined

**Comment by rishavanand** [comment]
I fixed that issue yesterday [here](https://github.com/rishavanand/github-profilinator/commit/b9999e65b591ae172e3da2b1c1924201de31a646). Could you rebase and check again?

**Comment by stspasow** [comment]
Done. I think it is ok now.

**Comment by rishavanand** [comment]
Still, there is some problem, only one section is able to convert into an accordion at a time. Also, the converted section automatically moves to the top of the preview instead of retaining its position.

**Comment by stspasow** [comment]
Sorry, I could not reproduce what you described, but passing just activeSectionIndex made the switches unswitcheble. Could you check if this is ok with you?

**Comment by rishavanand** [comment]
True that! the switches are not working as intended. I'll fix it and then we can move forward with collapsable sections.

**Comment by rishavanand** [comment]
I've fixed it. Could you merge the changes and check if collapsible sections are working?

**Comment by stspasow** [comment]
Yup, they look ok.

**Comment by rishavanand** [comment]
I've been a bit busy lately. Thank you for being patient, will review your commits soon.

**Review by rishavanand — APPROVED** [review]
LGTM! Thanks a ton! 🎉

**Pull request merged**
