### PR TITLE
Added label to the input fields in the "Connect with me" page

### LINKED ISSUE #45: fields do not show placeholder after textarea conversion
**Describe the bug**
During the input to textarea conversion, placeholders got left out.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the social(connect with me) section
4. See missing placeholders on all text areas

**Expected behavior**
Text areas are supposed to show placeholders as there are no labels

**Screenshots**
none

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser chrome

### PR DESCRIPTION
**Pull request by thomaslian**
Issue #45 stated that the text does not have a placeholder. A label would be better as stated in #47.

The "Connect with me" page, with the document SocialField.tsx was changed:
- Added "Form.Item" with a label to the existing "TextArea" to match similar design on other pages.
- Set the layout of the Form as vertical to match similar design on other pages.

This fixes #45 and closes #47

### CODE REVIEW

**Comment by rishavanand** [comment]
@thomaslian the build is failing, you'll have to shift the `key` prop from `TextArea` to `Form.Item` to resolve this error. To check the build process on your system you can run `npm run lint` and `npm run build` commands. Also after everything is done please rebase and push.

**Comment by thomaslian** [comment]
@rishavanand Yes I just saw, sorry about that. Should be fixed now

**Comment by rishavanand** [comment]
@thomaslian Looks perfect, there are two more things we need to do before merging and that is a squash and a rebase. Please rebase from the upstream dev branch and then squash all your commits into one. You might have to resolve some conflicts.

**Comment by thomaslian** [comment]
Okay, done

**Review by rishavanand — APPROVED** [review]
LGTM! 👍

**Pull request merged**
