### PR TITLE
scroll added in section and preview instead of main container.

### LINKED ISSUE #4: Add separate scroll to preview panel
**Is your feature request related to a problem? Please describe.**
It's frustating to have to scroll back to the top to see the changes in the preview panel while working with larger number of fields in the same section. To make a change in the last field, you have to scroll down to the bottom and then again scroll up to see the changes.

**Describe the solution you'd like**
Separate scroll bars for sections and preview should improve the UX.

**Describe alternatives you've considered**
None

**Additional context**
Suggested by @nitishk72 on [DEV.to](https://dev.to/nitishk72/comment/13cng)

### PR DESCRIPTION
**Pull request by smkamranqadri**
Fixed #4 

Screenshot 2020-10-08 at 12 33 52 AM

### CODE REVIEW

**Comment by rishavanand** [comment]
Hey @smkamranqadri, the scroll works perfectly but I see a few css errors, could you please fix it before we merge.

1. There is slight whitespace below the sidebar
2. The main two columns are not stretched out 100%

Screenshot 2020-10-08 at 9 55 10 AM

**Comment by smkamranqadri** [comment]
@rishavanand please check below

1. Noted and doing.
2. That's margin bottom, should I remove it like stretch containers to end no space between container and page?

**Comment by rishavanand** [comment]
@smkamranqadri for the first smaller red box, I recommend setting the sidebar height to `100vh`, whitespace of few pixels is still visible below the sidebar on my macOS-Chrome-v85. For the second larger red box I recommend stretching the heights of both the column(sections column and preview column) to `bottom - 1.5rem` so that the extra space vanishes.

**Comment by smkamranqadri** [comment]
Well, 1.5 rem is less since, we I have setting 100vh and less 150px which is the area from top section.

Screenshot 2020-10-08 at 10 53 20 PM

**Review by rishavanand — APPROVED** [review]
LGTM, thanks a lot 😄

**Pull request merged**
